// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
package org.usfirst.frc692.AerialAssist2014.subsystems;
import org.usfirst.frc692.AerialAssist2014.RobotMap;
import org.usfirst.frc692.AerialAssist2014.commands.*;
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;
/**
 *
 */
public class PneumaticsForPasserPusher extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    DoubleSolenoid passerPusher = RobotMap.pneumaticsForPasserPusherpasserPusher;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
    
    public void pushBallToPass()
    {
        passerPusher.set(DoubleSolenoid.Value.kForward);
    }
    //the piston will push the ball forward to get ready to pass
    //AO 1/25/14
    
    public void pusherGoBack()
    {
        passerPusher.set(DoubleSolenoid.Value.kReverse);
    }
    //The pusher will go back
    //AC 1/25/14
    
    public void pusherAirStop()
    {
        passerPusher.set(DoubleSolenoid.Value.kOff);
    }
    //The air will stop going through the solenoid that controls the pusher
    //AC 1/25/14
}
