// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
package org.usfirst.frc692.AerialAssist2014.commands;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc692.AerialAssist2014.Robot;
/**
 *
 */
public class  PassBall extends Command {
    public PassBall() {
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);
	
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.gatherer);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }
    // Called just before this Command runs the first time
    
    protected void initialize() {
        setTimeout(1.0);
    }
    /* will wait / have a delay of 1.0 second, then do the command
     * EV 1/27/14
     */
    
    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
        Robot.gatherer.gatherMotorReverse();
    }
    /* tells gather motor to go reverse in order to pass ball
     * EV 1/27/14
     */
    
    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return isTimedOut();
    }
    /*
     * finish delay of 1.0 second
     * EV 1/27/14
     */
    
    // Called once after isFinished returns true
    protected void end() {
        Robot.gatherer.gatherMotorStop();
    }
    //Gatherer motor will move in reverse direction for one second
    //AC 1/25/14
    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    
    protected void interrupted() {
    }
}
